steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/weather-repo/weather-app', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/weather-repo/weather-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'weather-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/weather-repo/weather-app'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=WEATHER_API_KEY=3716b0aee2851aa802b22bef0dc81b71'

options:
  logging: CLOUD_LOGGING_ONLY